language: python
python:
  - '3.7'

# 项目所在分支
branches:
  only:
  - master

install:
  - pip install -r requirements.txt

script:
  - python company_info.py

after_success:
  - git add --all ./doc/*
  - git commit -m "[skip travis] auto run by travis-ci"
  - git push https://actors315:$GITHUB_NET_TOKEN@github.com/A   actors315/enfsolar.spider.git --all

